# Generated by Django 2.2.13 on 2022-12-26 15:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20221225_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document',
            field=models.FileField(default=django.utils.timezone.now, upload_to='', verbose_name='documents/pdf'),
            preserve_default=False,
        ),
    ]
