# Generated by Django 2.2.13 on 2022-12-29 17:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0008_auto_20221227_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='likes',
            field=models.ManyToManyField(related_name='document_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
