# Generated by Django 2.2.13 on 2022-12-29 18:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0009_document_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='downloads',
            field=models.ManyToManyField(related_name='document_download', to=settings.AUTH_USER_MODEL),
        ),
    ]
